// <auto-generated />
using System;
using Market.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Market.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251104234111_migracija")]
    partial class migracija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorsBooks", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("BookAuthors", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 3
                        });
                });

            modelBuilder.Entity("BooksCategories", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("BooksCategories", (string)null);

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 1,
                            CategoriesId = 2
                        },
                        new
                        {
                            BooksId = 2,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 3,
                            CategoriesId = 3
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Addresses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Mostar",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 10, 893, DateTimeKind.Local).AddTicks(8513),
                            IsDeleted = false,
                            Line1 = "Maršala Tita"
                        },
                        new
                        {
                            Id = 2,
                            City = "Sarajevo",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 10, 893, DateTimeKind.Local).AddTicks(8571),
                            IsDeleted = false,
                            Line1 = "Vrbanja 1"
                        },
                        new
                        {
                            Id = 3,
                            City = "Jablanica",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 10, 893, DateTimeKind.Local).AddTicks(8573),
                            IsDeleted = false,
                            Line1 = "Gornja Kolonija SP 100"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Authors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "biografija",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(7396),
                            FirstName = "Meša",
                            IsDeleted = false,
                            LastName = "Selimović"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "biografija",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(7402),
                            FirstName = "Ivo",
                            IsDeleted = false,
                            LastName = "Andrić"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "biografija",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(7452),
                            FirstName = "Branko",
                            IsDeleted = false,
                            LastName = "Ćopić"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.BookFormats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BookFormats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(6388),
                            Format = "Tvrdi uvez",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(6395),
                            Format = "Tvrdi papirni uvez",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(6398),
                            Format = "Spiralni uvez",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookFormatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityInStockForOnlineOrders")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookFormatId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookFormatId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(6674),
                            Description = "A story about a young man, Holden Caulfield, and his experiences in New York City after being expelled from prep school.",
                            ISBN = "978-0-316-76948-0",
                            ImageUrl = "https://example.com/images/catcher_in_the_rye.jpg",
                            IsDeleted = false,
                            Language = "English",
                            PageCount = 277,
                            Price = 19.99m,
                            PublishedDate = new DateTime(1951, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 1,
                            QuantityInStockForOnlineOrders = 150,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 2,
                            BookFormatId = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(7074),
                            Description = "A fantasy novel by J.R.R. Tolkien, following the adventures of Bilbo Baggins in Middle-earth.",
                            ISBN = "978-0-618-00221-3",
                            ImageUrl = "https://example.com/images/the_hobbit.jpg",
                            IsDeleted = false,
                            Language = "English",
                            PageCount = 310,
                            Price = 25.99m,
                            PublishedDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 2,
                            QuantityInStockForOnlineOrders = 120,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 3,
                            BookFormatId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(7094),
                            Description = "A spiritual guidebook written by a spiritual teacher, exploring hidden knowledge and insights, offering guidance on life, peace, and inner wisdom.",
                            ISBN = "978-1-84293-719-6",
                            ImageUrl = "https://example.com/images/the_secret_of_secrets.jpg",
                            IsDeleted = false,
                            Language = "English",
                            PageCount = 400,
                            Price = 19.99m,
                            PublishedDate = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 2,
                            QuantityInStockForOnlineOrders = 150,
                            Title = "The Secret of Secrets"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(7313),
                            IsDeleted = false,
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(7321),
                            IsDeleted = false,
                            Name = "Poezija"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(7325),
                            IsDeleted = false,
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Publishers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sarajevo",
                            Country = "Bosna i Hercegovina",
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(6476),
                            IsDeleted = false,
                            Name = "Buybook"
                        },
                        new
                        {
                            Id = 2,
                            City = "Sarajevo",
                            Country = "Bosna i Hercegovina",
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(6482),
                            IsDeleted = false,
                            Name = "Svjetlost"
                        },
                        new
                        {
                            Id = 3,
                            City = "Beograd",
                            Country = "Srbija",
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(6575),
                            IsDeleted = false,
                            Name = "Laguna"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 10, 962, DateTimeKind.Local).AddTicks(8562),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            IsAdmin = true,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = false,
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEDpFy8DMpKVMC+oIkpDOs0RE3enMJ9U//mgEj7qrc3mpxltShFq2NgJU9wSWLlPR9A==",
                            TokenVersion = 0
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 31, DateTimeKind.Local).AddTicks(7534),
                            Email = "string@gmail.com",
                            FirstName = "string",
                            IsAdmin = false,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = false,
                            LastName = "string",
                            PasswordHash = "AQAAAAIAAYagAAAAEF3xbcAIABGnWwpYwbNWukXFm4aNbmx3DinHiY9vxr9cSQCD2k8UWVH152Fabwh5vw==",
                            TokenVersion = 0
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 5, 0, 41, 11, 109, DateTimeKind.Local).AddTicks(5569),
                            Email = "string@gmail.com",
                            FirstName = "manager@market.local",
                            IsAdmin = false,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = true,
                            LastName = "string",
                            PasswordHash = "AQAAAAIAAYagAAAAEIo3fRoWVJ9quQ5lH2xlv7auqYJoYQrDz9B1M/OKQrWqfqrd3rM/iCcu0BRPUJMdlQ==",
                            TokenVersion = 0
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.RefreshTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AuthorsBooks", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Authors", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.Books", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BooksCategories", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Books", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.Categories", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Books", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.BookFormats", "BookFormat")
                        .WithMany()
                        .HasForeignKey("BookFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.Publishers", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookFormat");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductEntity", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.ProductCategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Addresses", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.RefreshTokenEntity", b =>
                {
                    b.HasOne("Market.Domain.Entities.Identity.MarketUserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductCategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
