// <auto-generated />
using System;
using Market.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Market.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260315191121_AddCancelledAtAttributeToOrder")]
    partial class AddCancelledAtAttributeToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorBooks", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("BookAuthors", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 3
                        });
                });

            modelBuilder.Entity("BooksCategory", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("BooksCategories", (string)null);

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 1,
                            CategoriesId = 2
                        },
                        new
                        {
                            BooksId = 2,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 3,
                            CategoriesId = 3
                        });
                });

            modelBuilder.Entity("CouponsOrders", b =>
                {
                    b.Property<int>("CouponsId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.HasKey("CouponsId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("OrderCoupons", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Mostar",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 19, 992, DateTimeKind.Local).AddTicks(6435),
                            IsDeleted = false,
                            Line1 = "Maršala Tita"
                        },
                        new
                        {
                            Id = 2,
                            City = "Sarajevo",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 19, 992, DateTimeKind.Local).AddTicks(6584),
                            IsDeleted = false,
                            Line1 = "Vrbanja 1"
                        },
                        new
                        {
                            Id = 3,
                            City = "Jablanica",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 19, 992, DateTimeKind.Local).AddTicks(6592),
                            IsDeleted = false,
                            Line1 = "Gornja Kolonija SP 100"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "biografija",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1634),
                            FirstName = "Meša",
                            IsDeleted = false,
                            LastName = "Selimović"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "biografija",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1651),
                            FirstName = "Ivo",
                            IsDeleted = false,
                            LastName = "Andrić"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "biografija",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1656),
                            FirstName = "Branko",
                            IsDeleted = false,
                            LastName = "Ćopić"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.BookFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BookFormats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1126),
                            Format = "Tvrdi uvez",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1134),
                            Format = "Tvrdi papirni uvez",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1139),
                            Format = "Spiralni uvez",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookFormatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityInStockForOnlineOrders")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("BookFormatId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookFormatId = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1800),
                            Description = "Roman koji se bavi pitanjima vjere, duhovnosti i smrti, kroz priču o Dervišu koji pokušava da pronađe smisao u životu i smrti. Kroz likove i filozofske dijaloge, autor istražuje moralne dileme i ljudsku patnju.",
                            ISBN = "978-86-03-02636-0",
                            ImageUrl = "https://www.knjiga.ba/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/slike/dervis_i_smrt_logos_art.jpg",
                            IsDeleted = false,
                            Language = "Bosanski",
                            PageCount = 320,
                            Price = 29.99m,
                            PublishedDate = new DateTime(1966, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 1,
                            QuantityInStockForOnlineOrders = 200,
                            Title = "Derviš i smrt"
                        },
                        new
                        {
                            Id = 2,
                            BookFormatId = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1823),
                            Description = "Roman koji opisuje istoriju jednog grada i njegove mostove, kroz sudbine ljudi koji su živeli u različitim vremenima. Andrić istražuje ljudsku sudbinu, istoriju i političke i kulturne promene kroz život mosta na Drini.",
                            ISBN = "978-86-07-00752-2",
                            ImageUrl = "https://www.knjiga.ba/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/slike/d0977_na_drini_cuprija.jpg",
                            IsDeleted = false,
                            Language = "Bosanski",
                            PageCount = 412,
                            Price = 34.99m,
                            PublishedDate = new DateTime(1945, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 2,
                            QuantityInStockForOnlineOrders = 150,
                            Title = "Na Drini ćuprija"
                        },
                        new
                        {
                            Id = 3,
                            BookFormatId = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1832),
                            Description = "Roman koji kroz priču o životu jednog mladog čoveka istražuje teme ljubavi, smrti, i socijalnih promjena. Ćopić se bavi i univerzalnim pitanjima identiteta i postojanja u svetu koji se menja.",
                            ISBN = "978-86-03-00942-5",
                            ImageUrl = "https://www.knjiga.ba/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/slike/basta_pepeo.jpg",
                            IsDeleted = false,
                            Language = "Bosanski",
                            PageCount = 280,
                            Price = 24.99m,
                            PublishedDate = new DateTime(1954, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 3,
                            QuantityInStockForOnlineOrders = 120,
                            Title = "Bašta, pepeo"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1453),
                            IsDeleted = false,
                            IsEnabled = false,
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1482),
                            IsDeleted = false,
                            IsEnabled = false,
                            Name = "Poezija"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1488),
                            IsDeleted = false,
                            IsEnabled = false,
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ChangeTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChangeTypes");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.InventoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ChangeTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantityChanged")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ChangeTypeId");

                    b.ToTable("InventoryLog");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sarajevo",
                            Country = "Bosna i Hercegovina",
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1292),
                            IsDeleted = false,
                            Name = "Buybook"
                        },
                        new
                        {
                            Id = 2,
                            City = "Sarajevo",
                            Country = "Bosna i Hercegovina",
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1298),
                            IsDeleted = false,
                            Name = "Svjetlost"
                        },
                        new
                        {
                            Id = 3,
                            City = "Beograd",
                            Country = "Srbija",
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(1314),
                            IsDeleted = false,
                            Name = "Laguna"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test@bookverse.ba",
                            IsDeleted = false,
                            OpeningHours = "Mon-Fri 9am-9pm; Sat-Sun 10am-6pm",
                            Phone = "123-456-7890",
                            StoreName = "Central Bookstore"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test2@bookverse.ba",
                            IsDeleted = false,
                            OpeningHours = "Mon-Fri 9am-9pm; Sat-Sun 10am-6pm",
                            Phone = "123-456-7890",
                            StoreName = "Fortica Books"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test3@bookverse.ba",
                            IsDeleted = false,
                            OpeningHours = "Mon-Fri 9am-9pm; Sat-Sun 10am-6pm",
                            Phone = "123-456-7890",
                            StoreName = "Space Bookstore"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.StoreInventory", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastRestocked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<int>("ReorderTreshold")
                        .HasColumnType("int");

                    b.HasKey("StoreId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("StoreInventory");

                    b.HasData(
                        new
                        {
                            StoreId = 1,
                            BookId = 1,
                            IsDeleted = false,
                            LastRestocked = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3013),
                            Location = "Polica A-5",
                            QuantityInStock = 50,
                            ReorderTreshold = 5
                        },
                        new
                        {
                            StoreId = 2,
                            BookId = 1,
                            IsDeleted = false,
                            LastRestocked = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3053),
                            Location = "Polica A-12",
                            QuantityInStock = 90,
                            ReorderTreshold = 5
                        },
                        new
                        {
                            StoreId = 3,
                            BookId = 1,
                            IsDeleted = false,
                            LastRestocked = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3060),
                            Location = "Polica A-15",
                            QuantityInStock = 40,
                            ReorderTreshold = 5
                        },
                        new
                        {
                            StoreId = 1,
                            BookId = 2,
                            IsDeleted = false,
                            LastRestocked = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3065),
                            Location = "Polica A-21",
                            QuantityInStock = 200,
                            ReorderTreshold = 5
                        },
                        new
                        {
                            StoreId = 2,
                            BookId = 2,
                            IsDeleted = false,
                            LastRestocked = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3070),
                            Location = "Polica A-22",
                            QuantityInStock = 210,
                            ReorderTreshold = 5
                        },
                        new
                        {
                            StoreId = 3,
                            BookId = 2,
                            IsDeleted = false,
                            LastRestocked = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3077),
                            Location = "Polica A-23",
                            QuantityInStock = 240,
                            ReorderTreshold = 5
                        },
                        new
                        {
                            StoreId = 1,
                            BookId = 3,
                            IsDeleted = false,
                            LastRestocked = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3082),
                            Location = "Polica A-31",
                            QuantityInStock = 70,
                            ReorderTreshold = 5
                        },
                        new
                        {
                            StoreId = 2,
                            BookId = 3,
                            IsDeleted = false,
                            LastRestocked = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3088),
                            Location = "Polica A-32",
                            QuantityInStock = 90,
                            ReorderTreshold = 5
                        },
                        new
                        {
                            StoreId = 3,
                            BookId = 3,
                            IsDeleted = false,
                            LastRestocked = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3102),
                            Location = "Polica A-33",
                            QuantityInStock = 80,
                            ReorderTreshold = 5
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsManager")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TwoFactorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TwoFactorCodeExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 93, DateTimeKind.Local).AddTicks(7252),
                            Email = "admin@gmail.com",
                            FirstName = "admin",
                            IsAdmin = true,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = false,
                            LastName = "user",
                            PasswordHash = "AQAAAAIAAYagAAAAEL2kBq6kAd9148RCR8StqYBPOH+2oH5Fx5Obx25Iohpbf3Y/oJFpqZagmYQJUrKsrQ==",
                            TokenVersion = 0,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 194, DateTimeKind.Local).AddTicks(7342),
                            Email = "string",
                            FirstName = "string",
                            IsAdmin = false,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = false,
                            LastName = "string",
                            PasswordHash = "AQAAAAIAAYagAAAAEEb9Yv3LA2s2VZXrBGmsRwA2vaThUwV9KUlTzQpsvPZOK6vVUbfKZBQmYpm9H+n29g==",
                            TokenVersion = 0,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 15, 20, 11, 20, 292, DateTimeKind.Local).AddTicks(9609),
                            Email = "manager@gmail.com",
                            FirstName = "manager",
                            IsAdmin = false,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = true,
                            LastName = "user",
                            PasswordHash = "AQAAAAIAAYagAAAAEBbnCt4nIgR69DKAqKbi+CRKjxb0PYMAFq5qU2p6dg8iQAjNaN/6zS6NlSPOfTKFug==",
                            TokenVersion = 0,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.RefreshTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.CartItems", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("SavedForLater")
                        .HasColumnType("bit");

                    b.HasKey("CartId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.Carts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.Coupons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmountOff")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PercentOff")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromotionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Coupons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOff = 10m,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Welcome discount with amountoff 10",
                            EndDate = new DateTime(2027, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3249),
                            IsDeleted = false,
                            Name = "Welcome discount",
                            PromotionCode = "WELCOME10A",
                            StartDate = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3245)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Summer discount with percentoff 20",
                            EndDate = new DateTime(2027, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3282),
                            IsDeleted = false,
                            Name = "Summer discount ",
                            PercentOff = 20m,
                            PromotionCode = "WELCOME20P",
                            StartDate = new DateTime(2026, 3, 15, 20, 11, 20, 293, DateTimeKind.Local).AddTicks(3279)
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.OrderItems", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtTime")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusName")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StatusName = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StatusName = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StatusName = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StatusName = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StatusName = 5
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentSummaryId")
                        .HasColumnType("int");

                    b.Property<int?>("PickupStoreId")
                        .HasColumnType("int");

                    b.Property<int>("ShipToAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("ShippingMethodId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingPriceAtTheTime")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("PaymentSummaryId");

                    b.HasIndex("ShipToAddressId");

                    b.HasIndex("ShippingMethodId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.PaymentSummaries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Last4Digits")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PaymentSummaries", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.Refunds", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RefundDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderId", "BookId");

                    b.ToTable("Refunds", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.ShippingMethods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ShippingMethods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Domaća kurirska služba sa brzom dostavom na području cijele BiH (1–2 radna dana). Pogodno za pakete i dokumente.",
                            IsDeleted = false,
                            Name = "Express One",
                            Price = 9.50m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Brza pošta sa dostavom širom Bosne i Hercegovine u roku 24–48h. Često korištena za online trgovine.",
                            IsDeleted = false,
                            Name = "X Express",
                            Price = 8.00m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kurirska služba sa dostavom na području cijele BiH u roku 24–48h, uz mogućnost plaćanja pouzećem.",
                            IsDeleted = false,
                            Name = "EuroExpress",
                            Price = 9.00m
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.ShippingUpdates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("isCurrent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("ShippingUpdates", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.UserReviews.Review", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("BookId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            UserId = 1,
                            Comment = "Izuzetna knjiga koja me potpuno očarala. Meša Selimović majstorski oslikava duboke filozofske dileme i emocije likova, ostavljajući snažan utisak.",
                            DatePosted = new DateTime(2026, 3, 15, 19, 11, 20, 293, DateTimeKind.Utc).AddTicks(2017),
                            IsDeleted = false,
                            Rating = 5
                        },
                        new
                        {
                            BookId = 2,
                            UserId = 2,
                            Comment = "Dobra knjiga, ali nije me potpuno oduševila. Andrić je stvorio bogate likove i prikazao historijske procese, ali nekim dijelovima nedostaje dinamike.",
                            DatePosted = new DateTime(2026, 3, 15, 19, 11, 20, 293, DateTimeKind.Utc).AddTicks(2020),
                            IsDeleted = false,
                            Rating = 4
                        },
                        new
                        {
                            BookId = 3,
                            UserId = 3,
                            Comment = "Knjiga mi nije bila loša, ali nisam doživio neku posebnu emociju. Iako Ćopić piše o važnim temama, nisam se mogao potpuno povezati s likovima.",
                            DatePosted = new DateTime(2026, 3, 15, 19, 11, 20, 293, DateTimeKind.Utc).AddTicks(2023),
                            IsDeleted = false,
                            Rating = 3
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Whishlist.WishlistItems", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("AuthorBooks", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.Books", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BooksCategory", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Books", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CouponsOrders", b =>
                {
                    b.HasOne("Market.Domain.Entities.Shopping.Coupons", null)
                        .WithMany()
                        .HasForeignKey("CouponsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Shopping.Orders", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Books", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.BookFormat", "BookFormat")
                        .WithMany()
                        .HasForeignKey("BookFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookFormat");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.InventoryLog", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Books", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.ChangeTypes", "ChangeType")
                        .WithMany()
                        .HasForeignKey("ChangeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("ChangeType");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Store", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.StoreInventory", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Books", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.RefreshTokenEntity", b =>
                {
                    b.HasOne("Market.Domain.Entities.Identity.MarketUserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.CartItems", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Books", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Shopping.Carts", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.Carts", b =>
                {
                    b.HasOne("Market.Domain.Entities.Identity.MarketUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.OrderItems", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Books", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Shopping.Orders", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.Orders", b =>
                {
                    b.HasOne("Market.Domain.Entities.Shopping.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Shopping.PaymentSummaries", "PaymentSummary")
                        .WithMany()
                        .HasForeignKey("PaymentSummaryId");

                    b.HasOne("Market.Domain.Entities.Catalog.Address", "ShipToAddress")
                        .WithMany()
                        .HasForeignKey("ShipToAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Shopping.ShippingMethods", "ShippingMethod")
                        .WithMany()
                        .HasForeignKey("ShippingMethodId");

                    b.HasOne("Market.Domain.Entities.Identity.MarketUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("PaymentSummary");

                    b.Navigation("ShipToAddress");

                    b.Navigation("ShippingMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.Refunds", b =>
                {
                    b.HasOne("Market.Domain.Entities.Shopping.OrderItems", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "BookId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.ShippingUpdates", b =>
                {
                    b.HasOne("Market.Domain.Entities.Shopping.Orders", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Shopping.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Identity.MarketUserEntity", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderStatus");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Market.Domain.Entities.UserReviews.Review", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Books", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Identity.MarketUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Market.Domain.Entities.Whishlist.WishlistItems", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Books", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Identity.MarketUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.Carts", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Market.Domain.Entities.Shopping.Orders", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
