// <auto-generated />
using System;
using Market.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Market.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorsBooks", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("BookAuthors", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 3
                        });
                });

            modelBuilder.Entity("BooksCategories", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("BooksCategories", (string)null);

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 1,
                            CategoriesId = 2
                        },
                        new
                        {
                            BooksId = 2,
                            CategoriesId = 1
                        },
                        new
                        {
                            BooksId = 3,
                            CategoriesId = 3
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Addresses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Mostar",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 287, DateTimeKind.Local).AddTicks(1005),
                            IsDeleted = false,
                            Line1 = "Maršala Tita"
                        },
                        new
                        {
                            Id = 2,
                            City = "Sarajevo",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 287, DateTimeKind.Local).AddTicks(1109),
                            IsDeleted = false,
                            Line1 = "Vrbanja 1"
                        },
                        new
                        {
                            Id = 3,
                            City = "Jablanica",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 287, DateTimeKind.Local).AddTicks(1116),
                            IsDeleted = false,
                            Line1 = "Gornja Kolonija SP 100"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Authors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "biografija",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(3295),
                            FirstName = "Meša",
                            IsDeleted = false,
                            LastName = "Selimović"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "biografija",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(3327),
                            FirstName = "Ivo",
                            IsDeleted = false,
                            LastName = "Andrić"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "biografija",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(3337),
                            FirstName = "Branko",
                            IsDeleted = false,
                            LastName = "Ćopić"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.BookFormats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BookFormats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(2193),
                            Format = "Tvrdi uvez",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(2224),
                            Format = "Tvrdi papirni uvez",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(2234),
                            Format = "Spiralni uvez",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookFormatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityInStockForOnlineOrders")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookFormatId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookFormatId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(3516),
                            Description = "Roman koji se bavi pitanjima vjere, duhovnosti i smrti, kroz priču o Dervišu koji pokušava da pronađe smisao u životu i smrti. Kroz likove i filozofske dijaloge, autor istražuje moralne dileme i ljudsku patnju.",
                            ISBN = "978-86-03-02636-0",
                            ImageUrl = "https://example.com/images/dervis_i_smrt.jpg",
                            IsDeleted = false,
                            Language = "Bosanski",
                            PageCount = 320,
                            Price = 29.99m,
                            PublishedDate = new DateTime(1966, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 1,
                            QuantityInStockForOnlineOrders = 200,
                            Title = "Derviš i smrt"
                        },
                        new
                        {
                            Id = 2,
                            BookFormatId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(3555),
                            Description = "Roman koji opisuje istoriju jednog grada i njegove mostove, kroz sudbine ljudi koji su živeli u različitim vremenima. Andrić istražuje ljudsku sudbinu, istoriju i političke i kulturne promene kroz život mosta na Drini.",
                            ISBN = "978-86-07-00752-2",
                            ImageUrl = "https://example.com/images/na_drini_cuprija.jpg",
                            IsDeleted = false,
                            Language = "Bosanski",
                            PageCount = 412,
                            Price = 34.99m,
                            PublishedDate = new DateTime(1945, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 2,
                            QuantityInStockForOnlineOrders = 150,
                            Title = "Na Drini ćuprija"
                        },
                        new
                        {
                            Id = 3,
                            BookFormatId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(3569),
                            Description = "Roman koji kroz priču o životu jednog mladog čoveka istražuje teme ljubavi, smrti, i socijalnih promjena. Ćopić se bavi i univerzalnim pitanjima identiteta i postojanja u svetu koji se menja.",
                            ISBN = "978-86-03-00942-5",
                            ImageUrl = "https://example.com/images/basta_pepeo.jpg",
                            IsDeleted = false,
                            Language = "Bosanski",
                            PageCount = 280,
                            Price = 24.99m,
                            PublishedDate = new DateTime(1954, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 3,
                            QuantityInStockForOnlineOrders = 120,
                            Title = "Bašta, pepeo"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(2704),
                            IsDeleted = false,
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(2753),
                            IsDeleted = false,
                            Name = "Poezija"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(2824),
                            IsDeleted = false,
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Publishers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sarajevo",
                            Country = "Bosna i Hercegovina",
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(2473),
                            IsDeleted = false,
                            Name = "Buybook"
                        },
                        new
                        {
                            Id = 2,
                            City = "Sarajevo",
                            Country = "Bosna i Hercegovina",
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(2485),
                            IsDeleted = false,
                            Name = "Svjetlost"
                        },
                        new
                        {
                            Id = 3,
                            City = "Beograd",
                            Country = "Srbija",
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(2508),
                            IsDeleted = false,
                            Name = "Laguna"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 400, DateTimeKind.Local).AddTicks(4948),
                            Email = "admin@gmail.com",
                            FirstName = "admin",
                            IsAdmin = true,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = false,
                            LastName = "user",
                            PasswordHash = "AQAAAAIAAYagAAAAEJLNNCQgDkUHbicyfwARxLg8/Fn42K1Lu1w7cesAK1Ie9yeWqsXHkNKXv8H1W+Rq5w==",
                            TokenVersion = 0
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 508, DateTimeKind.Local).AddTicks(3361),
                            Email = "string",
                            FirstName = "string",
                            IsAdmin = false,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = false,
                            LastName = "string",
                            PasswordHash = "AQAAAAIAAYagAAAAECF7GgJUvjWc4YJeUBGN2t86q9HZYyP3L95+ZElMUX5LqWBU4d3JVrWBzYQF0wezbw==",
                            TokenVersion = 0
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 9, 18, 25, 55, 618, DateTimeKind.Local).AddTicks(767),
                            Email = "manager@gmail.com",
                            FirstName = "manager",
                            IsAdmin = false,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = true,
                            LastName = "user",
                            PasswordHash = "AQAAAAIAAYagAAAAEOLssaqh6Z0Q5BtH9570nClqGKqJ6aYmTT62NcLdvBDszfqfchBdiNO7BRGC0PryBg==",
                            TokenVersion = 0
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.RefreshTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Market.Domain.Entities.Review.Reviews", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("BookId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            UserId = 1,
                            Comment = "Izuzetna knjiga koja me potpuno očarala. Meša Selimović majstorski oslikava duboke filozofske dileme i emocije likova, ostavljajući snažan utisak.",
                            DatePosted = new DateTime(2025, 11, 9, 17, 25, 55, 618, DateTimeKind.Utc).AddTicks(3812),
                            IsDeleted = false,
                            Rating = 5
                        },
                        new
                        {
                            BookId = 2,
                            UserId = 2,
                            Comment = "Dobra knjiga, ali nije me potpuno oduševila. Andrić je stvorio bogate likove i prikazao historijske procese, ali nekim dijelovima nedostaje dinamike.",
                            DatePosted = new DateTime(2025, 11, 9, 17, 25, 55, 618, DateTimeKind.Utc).AddTicks(3817),
                            IsDeleted = false,
                            Rating = 4
                        },
                        new
                        {
                            BookId = 3,
                            UserId = 3,
                            Comment = "Knjiga mi nije bila loša, ali nisam doživio neku posebnu emociju. Iako Ćopić piše o važnim temama, nisam se mogao potpuno povezati s likovima.",
                            DatePosted = new DateTime(2025, 11, 9, 17, 25, 55, 618, DateTimeKind.Utc).AddTicks(3821),
                            IsDeleted = false,
                            Rating = 3
                        });
                });

            modelBuilder.Entity("AuthorsBooks", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Authors", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.Books", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BooksCategories", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Books", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.Categories", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Books", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.BookFormats", "BookFormat")
                        .WithMany()
                        .HasForeignKey("BookFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.Publishers", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookFormat");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductEntity", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.ProductCategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Addresses", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.RefreshTokenEntity", b =>
                {
                    b.HasOne("Market.Domain.Entities.Identity.MarketUserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Market.Domain.Entities.Review.Reviews", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Books", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Identity.MarketUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductCategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
