// <auto-generated />
using System;
using Market.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Market.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Addresses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Mostar",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 53, 717, DateTimeKind.Local).AddTicks(8084),
                            IsDeleted = false,
                            Line1 = "Maršala Tita"
                        },
                        new
                        {
                            Id = 2,
                            City = "Sarajevo",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 53, 717, DateTimeKind.Local).AddTicks(8290),
                            IsDeleted = false,
                            Line1 = "Vrbanja 1"
                        },
                        new
                        {
                            Id = 3,
                            City = "Jablanica",
                            Country = "BiH",
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 53, 717, DateTimeKind.Local).AddTicks(8303),
                            IsDeleted = false,
                            Line1 = "Gornja Kolonija SP 100"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.BookFormats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BookFormats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 54, 190, DateTimeKind.Local).AddTicks(9384),
                            Format = "Tvrdi uvez",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 54, 190, DateTimeKind.Local).AddTicks(9416),
                            Format = "Tvrdi papirni uvez",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 54, 190, DateTimeKind.Local).AddTicks(9424),
                            Format = "Spiralni uvez",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookFormatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityInStockForOnlineOrders")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookFormatId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookFormatId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 54, 191, DateTimeKind.Local).AddTicks(732),
                            Description = "A story about a young man, Holden Caulfield, and his experiences in New York City after being expelled from prep school.",
                            ISBN = "978-0-316-76948-0",
                            ImageUrl = "https://example.com/images/catcher_in_the_rye.jpg",
                            IsDeleted = false,
                            Language = "English",
                            PageCount = 277,
                            Price = 19.99m,
                            PublishedDate = new DateTime(1951, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 1,
                            QuantityInStockForOnlineOrders = 150,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 2,
                            BookFormatId = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 54, 191, DateTimeKind.Local).AddTicks(795),
                            Description = "A fantasy novel by J.R.R. Tolkien, following the adventures of Bilbo Baggins in Middle-earth.",
                            ISBN = "978-0-618-00221-3",
                            ImageUrl = "https://example.com/images/the_hobbit.jpg",
                            IsDeleted = false,
                            Language = "English",
                            PageCount = 310,
                            Price = 25.99m,
                            PublishedDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 2,
                            QuantityInStockForOnlineOrders = 120,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 3,
                            BookFormatId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 54, 191, DateTimeKind.Local).AddTicks(813),
                            Description = "A spiritual guidebook written by a spiritual teacher, exploring hidden knowledge and insights, offering guidance on life, peace, and inner wisdom.",
                            ISBN = "978-1-84293-719-6",
                            ImageUrl = "https://example.com/images/the_secret_of_secrets.jpg",
                            IsDeleted = false,
                            Language = "English",
                            PageCount = 400,
                            Price = 19.99m,
                            PublishedDate = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 2,
                            QuantityInStockForOnlineOrders = 150,
                            Title = "The Secret of Secrets"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Publishers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sarajevo",
                            Country = "Bosna i Hercegovina",
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 54, 191, DateTimeKind.Local).AddTicks(305),
                            IsDeleted = false,
                            Name = "Buybook"
                        },
                        new
                        {
                            Id = 2,
                            City = "Sarajevo",
                            Country = "Bosna i Hercegovina",
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 54, 191, DateTimeKind.Local).AddTicks(323),
                            IsDeleted = false,
                            Name = "Svjetlost"
                        },
                        new
                        {
                            Id = 3,
                            City = "Beograd",
                            Country = "Srbija",
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 54, 191, DateTimeKind.Local).AddTicks(346),
                            IsDeleted = false,
                            Name = "Laguna"
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 53, 844, DateTimeKind.Local).AddTicks(9419),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            IsAdmin = true,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = false,
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEPE2su9uoeaEyHtQezhMdcDemCZZX3YBFqUmsr1uBwvIJUzGx4EQAiBL3PTOJEkAqw==",
                            TokenVersion = 0
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 54, 16, DateTimeKind.Local).AddTicks(7009),
                            Email = "string@gmail.com",
                            FirstName = "string",
                            IsAdmin = false,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = false,
                            LastName = "string",
                            PasswordHash = "AQAAAAIAAYagAAAAENFKjAMozE+EG9N4sAepTPtcRYnPaA3aJqlVAB7NOMqCOfG4mJO5VEXX2nYDutWqhA==",
                            TokenVersion = 0
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 2,
                            CreatedAtUtc = new DateTime(2025, 11, 2, 17, 2, 54, 190, DateTimeKind.Local).AddTicks(7608),
                            Email = "string@gmail.com",
                            FirstName = "manager@market.local",
                            IsAdmin = false,
                            IsDeleted = false,
                            IsEmployee = true,
                            IsEnabled = true,
                            IsManager = true,
                            LastName = "string",
                            PasswordHash = "AQAAAAIAAYagAAAAEI/mZgFdszRoye3g7Rc36FA37a85Zeo2UKHkn9sYFZMcJtYgDujoCfShJF3STiX5pg==",
                            TokenVersion = 0
                        });
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.RefreshTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.Books", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.BookFormats", "BookFormat")
                        .WithMany()
                        .HasForeignKey("BookFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Market.Domain.Entities.Catalog.Publishers", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookFormat");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductEntity", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.ProductCategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.HasOne("Market.Domain.Entities.Catalog.Addresses", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.RefreshTokenEntity", b =>
                {
                    b.HasOne("Market.Domain.Entities.Identity.MarketUserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Market.Domain.Entities.Catalog.ProductCategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Market.Domain.Entities.Identity.MarketUserEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
